### ISSUE TITLE
Unfortunately, the project does not work.

### ISSUE THREAD

**Issue by juhacz** [Javinator9889/acexy#2] opened 2024-11-24 10:27 UTC
Hi, I was interested in your project, I tried to test it, but unfortunately it doesn't work.
Specifically, the Acestream server itself works, but the proxy server doesn't.

My Stack:
```
services:
 acexy:
 image: ghcr.io/javinator9889/acexy
 ports:
 - "8080:8080"
 - "6878:6878"
 environment:
 ACEXY_LISTEN_ADDR: ":8080" # Listen on port 8080
 ACEXY_SCHEME: "http" # Use HTTP
 ACEXY_HOST: "localhost" # Host is localhost
 ACEXY_PORT: "6878" # Port is 6878
 ACEXY_M3U8_STREAM_TIMEOUT: "60s" # Timeout is 60 seconds when in M3U8 mode
 ACEXY_M3U8: "false" # Disable M3U8 mode

```

I checked the individual endpoints from a web browser and here are the results:
http://192.168.100.130:8080/
"404 page not found"

http://192.168.100.130:6878/ace/getstream?infohash=8f92d328d2e5a8a83f04bd6f3da38bf48a37e375
Stream working.

http://192.168.100.130:6878/ace/getstream?id=8f92d328d2e5a8a83f04bd6f3da38bf48a37e375
"failed to load content"

http://192.168.100.130:8080/ace/getstream?id=8f92d328d2e5a8a83f04bd6f3da38bf48a37e375
Browser error: ERR_EMPTY_RESPONSE

Below is the container log, maybe you can diagnose what the problem is? The project looks promising because of the ability to play the same stream on many devices at the same time, aloe unfortunately does not work for me.

```

ls: cannot access '/dev/disk/by-id/': No such file or directory
ls: cannot access '/dev/disk/by-id/': No such file or directory
ls: cannot access '/dev/disk/by-id/': No such file or directory
ls: cannot access '/dev/disk/by-id/': No such file or directory
ls: cannot access '/dev/disk/by-id/': No such file or directory
2024-11-24 10:07:10,685|MainThread|acestream.coreapp|set_debug_from_ui: level=0
2024-11-24 10:07:10,685|MainThread|acestream|enable debug: 0
2024-11-24 10:07:10,686|MainThread|acestream|set debug level: 0
2024-11-24 10:07:10,692|MainThread|acestream.coreapp|cannot load session config, use default
2024-11-24 10:07:10,706|MainThread|acestream.SocketHandler.InterruptSocket|bound on 127.0.0.1:54199
2024-11-24 10:07:10,706|MainThread|acestream.SocketHandler.SocketHandler|bind: socket bound: host=0.0.0.0 port=8621
2024-11-24 10:07:10,706|MainThread|acestream.LM|listen on 8621
2024-11-24 10:07:10,707|MainThread|acestream.localdb|No existing database found. Attempting to creating a new database '/root/.ACEStream/sqlite/torrentstream.sdb'
2024-11-24 10:07:10,739|MainThread|acestream.httpserver|start: addr= port=6878 allow_remote=0 allow_intranet=1
2024-11-24 10:07:10,740|MainThread|acestream.httpserver|start: bound on ('0.0.0.0', 6878)
2024-11-24 10:07:10,854|MainThread|acestream.SocketHandler.InterruptSocket|bound on 127.0.0.1:54925
2024-11-24 10:07:10,854|MainThread|acestream.SocketHandler.SocketHandler|bind: socket bound: host=0.0.0.0 port=62062
2024-11-24 10:07:10,855|Instance2InstanceThread-31|acestream.APIServer|run: ready to receive remote commands on 62062
2024-11-24 10:07:10,856|PlaylistTaskManagerThread-32 (_run)|acestream.TaskManager|started
2024-11-24 10:07:18,744|Thread-19 (__forward)|acestream.upnp|Unable to create Port Forward. Error: Success: <class 'Exception'>:Success
2024/11/24 10:15:00 INFO Temporary PID pid=96633d68-d181-489c-8521-434e7fb00115 stream=8f92d328d2e5a8a83f04bd6f3da38bf48a37e375
2024/11/24 10:15:01 WARN Error in stream response error="failed to load content"
2024/11/24 10:15:01 http: panic serving 192.168.100.3:3886: runtime error: invalid memory address or nil pointer dereference

goroutine 5 [running]:
net/http.(*conn).serve.func1()
	/usr/local/go/src/net/http/server.go:1903 +0xbe
panic({0x6bef60?, 0x956ee0?})
	/usr/local/go/src/runtime/panic.go:770 +0x132
javinator9889/acexy/lib/acexy.(*Acexy).FetchStream(0xc0000ea000, {0xc00001e066, 0x28}, 0xc00006c270)
	/app/lib/acexy/acexy.go:130 +0x310
main.(*Proxy).ServeHTTP(0xc000098038, {0x795a48, 0xc0001860e0}, 0xc000016480)
	/app/proxy.go:65 +0x22e
net/http.(*ServeMux).ServeHTTP(0x4661d9?, {0x795a48, 0xc0001860e0}, 0xc000016480)
	/usr/local/go/src/net/http/server.go:2688 +0x1ad
net/http.serverHandler.ServeHTTP({0xc00006c0c0?}, {0x795a48?, 0xc0001860e0?}, 0x6?)
	/usr/local/go/src/net/http/server.go:3142 +0x8e
net/http.(*conn).serve(0xc00006e000, {0x796080, 0xc00009acf0})
	/usr/local/go/src/net/http/server.go:2044 +0x5e8
created by net/http.(*Server).Serve in goroutine 1
	/usr/local/go/src/net/http/server.go:3290 +0x4b4
2024/11/24 10:15:01 INFO Temporary PID pid=c4c3a71f-360d-4336-87d1-da0823c99d4f stream=8f92d328d2e5a8a83f04bd6f3da38bf48a37e375
2024/11/24 10:15:02 WARN Error in stream response error="failed to load content"
2024/11/24 10:15:02 http: panic serving 192.168.100.3:3927: runtime error: invalid memory address or nil pointer dereference
goroutine 16 [running]:
net/http.(*conn).serve.func1()
	/usr/local/go/src/net/http/server.go:1903 +0xbe
panic({0x6bef60?, 0x956ee0?})
	/usr/local/go/src/runtime/panic.go:770 +0x132
javinator9889/acexy/lib/acexy.(*Acexy).FetchStream(0xc0000ea000, {0xc00001e1f6, 0x28}, 0xc00006cd50)
	/app/lib/acexy/acexy.go:130 +0x310
main.(*Proxy).ServeHTTP(0xc000098038, {0x795a48, 0xc0001861c0}, 0xc000016900)
	/app/proxy.go:65 +0x22e
net/http.(*ServeMux).ServeHTTP(0x4661d9?, {0x795a48, 0xc0001861c0}, 0xc000016900)
	/usr/local/go/src/net/http/server.go:2688 +0x1ad
net/http.serverHandler.ServeHTTP({0xc00006cc90?}, {0x795a48?, 0xc0001861c0?}, 0x6?)
	/usr/local/go/src/net/http/server.go:3142 +0x8e
net/http.(*conn).serve(0xc00006e5a0, {0x796080, 0xc00009acf0})
	/usr/local/go/src/net/http/server.go:2044 +0x5e8
created by net/http.(*Server).Serve in goroutine 1
	/usr/local/go/src/net/http/server.go:3290 +0x4b4
2024/11/24 10:15:03 INFO Temporary PID pid=b004abf6-63fb-4235-974a-728142f60179 stream=8f92d328d2e5a8a83f04bd6f3da38bf48a37e375
2024/11/24 10:15:04 WARN Error in stream response error="failed to load content"
2024/11/24 10:15:04 http: panic serving 192.168.100.3:3930: runtime error: invalid memory address or nil pointer dereference
goroutine 34 [running]:
net/http.(*conn).serve.func1()
	/usr/local/go/src/net/http/server.go:1903 +0xbe
panic({0x6bef60?, 0x956ee0?})
	/usr/local/go/src/runtime/panic.go:770 +0x132
javinator9889/acexy/lib/acexy.(*Acexy).FetchStream(0xc0000ea000, {0xc00012a016, 0x28}, 0xc00009af30)
	/app/lib/acexy/acexy.go:130 +0x310
main.(*Proxy).ServeHTTP(0xc000098038, {0x795a48, 0xc0000ec380}, 0xc0000ac5a0)
	/app/proxy.go:65 +0x22e
net/http.(*ServeMux).ServeHTTP(0x4661d9?, {0x795a48, 0xc0000ec380}, 0xc0000ac5a0)
	/usr/local/go/src/net/http/server.go:2688 +0x1ad
net/http.serverHandler.ServeHTTP({0xc00009ae70?}, {0x795a48?, 0xc0000ec380?}, 0x6?)
	/usr/local/go/src/net/http/server.go:3142 +0x8e
net/http.(*conn).serve(0xc00006e900, {0x796080, 0xc00009acf0})
	/usr/local/go/src/net/http/server.go:2044 +0x5e8
created by net/http.(*Server).Serve in goroutine 1
	/usr/local/go/src/net/http/server.go:3290 +0x4b4
2024/11/24 10:15:09 INFO Temporary PID pid=ac229f19-bb8c-4790-9ba6-3b9b321b13ec stream=8f92d328d2e5a8a83f04bd6f3da38bf48a37e375
2024/11/24 10:15:10 WARN Error in stream response error="failed to load content"
2024/11/24 10:15:10 http: panic serving 192.168.100.3:3931: runtime error: invalid memory address or nil pointer dereference
goroutine 35 [running]:
net/http.(*conn).serve.func1()
	/usr/local/go/src/net/http/server.go:1903 +0xbe
panic({0x6bef60?, 0x956ee0?})
	/usr/local/go/src/runtime/panic.go:770 +0x132
javinator9889/acexy/lib/acexy.(*Acexy).FetchStream(0xc0000ea000, {0xc00001e246, 0x28}, 0xc00006d110)
	/app/lib/acexy/acexy.go:130 +0x310
main.(*Proxy).ServeHTTP(0xc000098038, {0x795a48, 0xc0001862a0}, 0xc000016b40)
	/app/proxy.go:65 +0x22e
net/http.(*ServeMux).ServeHTTP(0x4661d9?, {0x795a48, 0xc0001862a0}, 0xc000016b40)
	/usr/local/go/src/net/http/server.go:2688 +0x1ad
net/http.serverHandler.ServeHTTP({0xc00006d050?}, {0x795a48?, 0xc0001862a0?}, 0x6?)
	/usr/local/go/src/net/http/server.go:3142 +0x8e
net/http.(*conn).serve(0xc00006eab0, {0x796080, 0xc00009acf0})
	/usr/local/go/src/net/http/server.go:2044 +0x5e8
created by net/http.(*Server).Serve in goroutine 1
	/usr/local/go/src/net/http/server.go:3290 +0x4b4


```

**Comment by Javinator9889** [comment] 2024-11-24 10:56
Hi!

Thanks for the report 😊
I was having a quick look and you're directly accessing the AceStream Engine behind the proxy, which is located at port `6878`

In order for the proxy to do its thing, you should do the same steps as the ones you were already doing but pointing to the proxy's port, `8080`.

Please, give it a try and let me know if it works. I'll update the documentation to point out that 😊

**Comment by Javinator9889** [comment] 2024-11-24 10:57
PS: @juhacz it seems the error you were getting happened because of accessing `/` I think

**Comment by juhacz** [comment] 2024-11-24 12:30
Hello, as I wrote, trying to access via port 8080 also does not work, the browser returns the error ERR_EMPTY_RESPONSE
http://192.168.100.130:8080/ace/getstream?id=8f92d328d2e5a8a83f04bd6f3da38bf48a37e375
I hope you can diagnose the problem.

**Comment by Javinator9889** [comment] 2024-11-24 19:18
Hello again @juhacz,

Thanks for the report. I have checked it carefully and ended up with a bugfix to add support to `infohash` streams - it was only possible to reproduce `id` streams. See #3.

Can you try it and verify it is working as expected? Here you have the instructions:

```bash
git clone -b bugfix/#2-nil-pointer https://github.com/Javinator9889/acexy.git
cd acexy
docker build . -t acexy:bugfix-2
```
> NOTE: This is assuming you're in the Docker group. You may need to run the `docker build` command as `root`

Then, taking the YAML file you provided, it will be a simple change of the service to test it:

```yml
services:
 acexy:
 image: acexy:bugfix-2
 ports:
 - "8080:8080"
 - "6878:6878"
 environment:
 ACEXY_LISTEN_ADDR: ":8080" # Listen on port 8080
 ACEXY_SCHEME: "http" # Use HTTP
 ACEXY_HOST: "localhost" # Host is localhost
 ACEXY_PORT: "6878" # Port is 6878
 ACEXY_M3U8_STREAM_TIMEOUT: "60s" # Timeout is 60 seconds when in M3U8 mode
 ACEXY_M3U8: "false" # Disable M3U8 mode
```

I have checked it locally and it seems to work fine. Using `id` is not possible due to the fact the `infohash` and `id` are not exchangeable between them.

**Comment by juhacz** [comment] 2024-11-24 20:02
Installation and quick tests show that everything now works correctly at the same time, on different devices. Thanks for the great work, if I notice any problems, I will report.
Best regards

**Comment by Javinator9889** [comment] 2024-11-24 20:13
Merged

Should be available under tag `0.1.1` in a few minutes

**Closed** 2024-11-24 20:13 UTC

**Comment by juhacz** [comment] 2024-11-24 21:54
@Javinator9889: I have noticed another problem that occurs when I try to use HLS mode. When I use ACEXY_M3U8: "true" and try to play the stream via http://192.168.100.130:8080/ace/getstream?infohash=8f92d328d2e5a8a83f04bd6f3da38bf48a37e375 the stream does not display, and in the logs I see as below:

```
ls: cannot access '/dev/disk/by-id/': No such file or directory
ls: cannot access '/dev/disk/by-id/': No such file or directory
ls: cannot access '/dev/disk/by-id/': No such file or directory
2024-11-24 21:46:48,060|MainThread|acestream.coreapp|set_debug_from_ui: level=0
2024-11-24 21:46:48,060|MainThread|acestream|enable debug: 0
2024-11-24 21:46:48,061|MainThread|acestream|set debug level: 0
2024-11-24 21:46:48,088|MainThread|acestream.SocketHandler.InterruptSocket|bound on 127.0.0.1:54882
2024-11-24 21:46:48,089|MainThread|acestream.SocketHandler.SocketHandler|bind: socket bound: host=0.0.0.0 port=8621
2024-11-24 21:46:48,089|MainThread|acestream.LM|listen on 8621
2024-11-24 21:46:48,116|MainThread|acestream.httpserver|start: addr= port=6878 allow_remote=0 allow_intranet=1
2024-11-24 21:46:48,116|MainThread|acestream.httpserver|start: bound on ('0.0.0.0', 6878)
2024-11-24 21:46:48,184|MainThread|acestream.SocketHandler.InterruptSocket|bound on 127.0.0.1:39379
2024-11-24 21:46:48,185|MainThread|acestream.SocketHandler.SocketHandler|bind: socket bound: host=0.0.0.0 port=62062
2024-11-24 21:46:48,187|Instance2InstanceThread-31|acestream.APIServer|run: ready to receive remote commands on 62062
2024-11-24 21:46:48,188|PlaylistTaskManagerThread-32 (_run)|acestream.TaskManager|started
2024-11-24 21:46:56,121|Thread-19 (__forward)|acestream.upnp|Unable to create Port Forward. Error: Success: <class 'Exception'>:Success
2024/11/24 21:47:03 INFO Temporary PID pid=d9ae33bb-38be-4e57-a99d-6e220623ad23 stream="{infohash: 8f92d328d2e5a8a83f04bd6f3da38bf48a37e375}"
2024/11/24 21:47:03 INFO Started new stream id="{infohash: 8f92d328d2e5a8a83f04bd6f3da38bf48a37e375}" clients=0
2024/11/24 21:47:21 INFO Reusing existing stream="{infohash: 8f92d328d2e5a8a83f04bd6f3da38bf48a37e375}" clients=1
2024/11/24 21:47:27 INFO Reusing existing stream="{infohash: 8f92d328d2e5a8a83f04bd6f3da38bf48a37e375}" clients=2
2024/11/24 21:47:31 INFO Reusing existing stream="{infohash: 8f92d328d2e5a8a83f04bd6f3da38bf48a37e375}" clients=3
2024/11/24 21:47:35 INFO Reusing existing stream="{infohash: 8f92d328d2e5a8a83f04bd6f3da38bf48a37e375}" clients=4
2024/11/24 21:47:43 INFO Reusing existing stream="{infohash: 8f92d328d2e5a8a83f04bd6f3da38bf48a37e375}" clients=5
2024/11/24 21:48:17 INFO Reusing existing stream="{infohash: 8f92d328d2e5a8a83f04bd6f3da38bf48a37e375}" clients=5
2024/11/24 21:48:22 INFO Reusing existing stream="{infohash: 8f92d328d2e5a8a83f04bd6f3da38bf48a37e375}" clients=5


```

**Comment by Javinator9889** [comment] 2024-11-24 22:25
> @Javinator9889: I have noticed another problem that occurs when I try to use HLS mode. When I use ACEXY_M3U8: "true" and try to play the stream via http://192.168.100.130:8080/ace/getstream?infohash=8f92d328d2e5a8a83f04bd6f3da38bf48a37e375 the stream does not display, and in the logs I see as below:
> 
> ```
> ls: cannot access '/dev/disk/by-id/': No such file or directory
> ls: cannot access '/dev/disk/by-id/': No such file or directory
> ls: cannot access '/dev/disk/by-id/': No such file or directory
> 2024-11-24 21:46:48,060|MainThread|acestream.coreapp|set_debug_from_ui: level=0
> 2024-11-24 21:46:48,060|MainThread|acestream|enable debug: 0
> 2024-11-24 21:46:48,061|MainThread|acestream|set debug level: 0
> 2024-11-24 21:46:48,088|MainThread|acestream.SocketHandler.InterruptSocket|bound on 127.0.0.1:54882
> 2024-11-24 21:46:48,089|MainThread|acestream.SocketHandler.SocketHandler|bind: socket bound: host=0.0.0.0 port=8621
> 2024-11-24 21:46:48,089|MainThread|acestream.LM|listen on 8621
> 2024-11-24 21:46:48,116|MainThread|acestream.httpserver|start: addr= port=6878 allow_remote=0 allow_intranet=1
> 2024-11-24 21:46:48,116|MainThread|acestream.httpserver|start: bound on ('0.0.0.0', 6878)
> 2024-11-24 21:46:48,184|MainThread|acestream.SocketHandler.InterruptSocket|bound on 127.0.0.1:39379
> 2024-11-24 21:46:48,185|MainThread|acestream.SocketHandler.SocketHandler|bind: socket bound: host=0.0.0.0 port=62062
> 2024-11-24 21:46:48,187|Instance2InstanceThread-31|acestream.APIServer|run: ready to receive remote commands on 62062
> 2024-11-24 21:46:48,188|PlaylistTaskManagerThread-32 (_run)|acestream.TaskManager|started
> 2024-11-24 21:46:56,121|Thread-19 (__forward)|acestream.upnp|Unable to create Port Forward. Error: Success: <class 'Exception'>:Success
> 2024/11/24 21:47:03 INFO Temporary PID pid=d9ae33bb-38be-4e57-a99d-6e220623ad23 stream="{infohash: 8f92d328d2e5a8a83f04bd6f3da38bf48a37e375}"
> 2024/11/24 21:47:03 INFO Started new stream id="{infohash: 8f92d328d2e5a8a83f04bd6f3da38bf48a37e375}" clients=0
> 2024/11/24 21:47:21 INFO Reusing existing stream="{infohash: 8f92d328d2e5a8a83f04bd6f3da38bf48a37e375}" clients=1
> 2024/11/24 21:47:27 INFO Reusing existing stream="{infohash: 8f92d328d2e5a8a83f04bd6f3da38bf48a37e375}" clients=2
> 2024/11/24 21:47:31 INFO Reusing existing stream="{infohash: 8f92d328d2e5a8a83f04bd6f3da38bf48a37e375}" clients=3
> 2024/11/24 21:47:35 INFO Reusing existing stream="{infohash: 8f92d328d2e5a8a83f04bd6f3da38bf48a37e375}" clients=4
> 2024/11/24 21:47:43 INFO Reusing existing stream="{infohash: 8f92d328d2e5a8a83f04bd6f3da38bf48a37e375}" clients=5
> 2024/11/24 21:48:17 INFO Reusing existing stream="{infohash: 8f92d328d2e5a8a83f04bd6f3da38bf48a37e375}" clients=5
> 2024/11/24 21:48:22 INFO Reusing existing stream="{infohash: 8f92d328d2e5a8a83f04bd6f3da38bf48a37e375}" clients=5
> 
> 
> ```
>       
>       
>     

HLS support is still in a pre-eliminary stage and I don't expect it to work fine

I'm still working into it, but it's not even behaving fine with the AceStream Engine at all

Thanks for reporting, I'll have it in sight 😊
